spring:
  application:
    name: kline-proxy
server:
  port: 1888
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  metrics:
    tags:
      application: ${spring.application.name}
number:
  type: double
kline:
  persistence:
    enabled: false
    loadOnStartup: true
    dumpOnShutdown: true
    dumpIntervalSeconds: 300
    rootDir: ./data/kline-cache
    spot:
      intervalConfigs:
        "1h":
          # default is minMaintainCount * 2 when omitted
          maxStoreCount: 2000
          symbolMaxStoreCounts:
            BTCUSDT: 4000
    future:
      intervalConfigs:
        "1h":
          # default is minMaintainCount * 2 when omitted
          maxStoreCount: 2000
  binance:
    spot:
      intervalSyncConfigs:
        "1h":
          minMaintainCount: 1000
          listenSymbolPatterns:
            - .*?USDT
        "1d":
          minMaintainCount: 365
          listenSymbolPatterns:
            - .*?USDT
    future:
      intervalSyncConfigs:
        "1h":
          minMaintainCount: 1000
          listenSymbolPatterns:
            - .*?USDT
        "1d":
          minMaintainCount: 365
          listenSymbolPatterns:
            - .*?USDT

client:
  binanceSpot:
    api:
      rootUrl: https://api.binance.com
  binanceFuture:
    api:
      rootUrl: https://fapi.binance.com

ws:
  client:
    binanceSpot:
      url: wss://stream.binance.com/ws
    binanceFuture:
      url: wss://fstream.binance.com/ws
