spring:
  application:
    name: kline-proxy
server:
  port: 1888
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  metrics:
    tags:
      application: ${spring.application.name}
number:
  type: double
kline:
  binance:
    spot:
      minMaintainCount: 5000
      listenIntervals:
        - "1h"
      listenSymbolPatterns:
        - .*?USDT
    future:
      minMaintainCount: 5000
      listenIntervals:
        - "1h"
      listenSymbolPatterns:
        - .*?USDT

client:
  binanceSpot:
    api:
      rootUrl: https://api.binance.com
  binanceFuture:
    api:
      rootUrl: https://fapi.binance.com

ws:
  client:
    binanceSpot:
      url: wss://stream.binance.com/ws
    binanceFuture:
      url: wss://fstream.binance.com/ws
