package com.zx.quant.klineproxy.model;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.io.SerializedString;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.AbstractList;
import java.util.List;
import java.util.RandomAccess;

/** Read-only response rows with JSON generated by the same numeric display conversion as before. */
@JsonSerialize(using = EncodedKlineRows.Encoder.class)
public final class EncodedKlineRows extends AbstractList<Object[]> implements RandomAccess {
  private final List<Object[]> rows;
  private final SerializedString json;
  private final int weight;

  public EncodedKlineRows(List<Object[]> rows, List<String> encodedRows) {
    this.rows = List.copyOf(rows);
    this.json = new SerializedString("[" + String.join(",", encodedRows) + "]");
    // Eagerly encode once, outside the series commit lock. Subsequent HTTP writes share bytes.
    this.json.asUnquotedUTF8();
    this.weight = 128 + json.getValue().length() * 3 + rows.size() * 16;
  }

  @Override
  public Object[] get(int index) {
    // Programmatic callers must not mutate formatting shared with other windows or ordinary
    // kline responses. The HTTP encoder below writes cached bytes without calling get().
    return rows.get(index).clone();
  }

  @Override
  public int size() {
    return rows.size();
  }

  public int estimatedWeight() {
    return weight;
  }

  public static final class Encoder extends JsonSerializer<EncodedKlineRows> {
    @Override
    public void serialize(EncodedKlineRows value, JsonGenerator generator,
        SerializerProvider serializers) throws IOException {
      generator.writeRawValue(value.json);
    }
  }
}
